name: CI
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - gather
    steps:
      - uses: actions/checkout@v2
      - name: PSVersion Table
        run: $psversiontable
      - name: Chocolatey Version
        run: choco --version
      - name: Validate ${{ matrix.package }} Build
        run: |
          & .\${{ matrix.package }}.ps1 -ValidateInstall -Verbose -ErrorAction Stop
